version: "3"

services:
    server:
        container_name: "server"
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            PORT: "${PORT}"
            SYSTEM_NAME: "${SYSTEM_NAME}"
            POSTGRES_HOSTNAME: "db"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_PORT: "${POSTGRES_PORT}"
            TZ: "${TZ}"
        ports:
            - "${HOSTPORT}:${PORT}"
        volumes:
            - ./server/app:/app
            - /app/node_modules
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:10
        container_name: "db"
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
            PGTZ: "${TZ}"
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./db/data:/var/lib/postgresql/data
            - ./db/initdb:/docker-entrypoint-initdb.d
        healthcheck:
            test: "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'select * from exams'"
            interval: 1s
            timeout: 1s
            retries: 0
            start_period: 20s
